# Generated by Django 4.0.6 on 2022-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('phonenumber', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
